### ISSUE TITLE
Can't set the same boolean variable for release and debug in an android project

### ISSUE THREAD

**Issue by jotkauser** [gmazzo/gradle-buildconfig-plugin#197]
```
    buildTypes {
        release {
            buildConfig {
                 buildConfigField("Boolean", "DEBUG", "false")
                 buildConfigField("String", "BUILD_TYPE", "\"release\"")
            }
        }
        debug {
            buildConfig {
                buildConfigField("Boolean", "DEBUG", "true")
                buildConfigField("String", "BUILD_TYPE", "\"debug\"")
            }
        }
    }
```
    
    When the release buildconfig is commented it works and when its uncommented it throws an error

**Comment by gmazzo** [comment]
This is a usage mistake since you are violating DSL scopes. 

`buildConfig {` is scoped at project's level. The fact you can invoke it from inside a `BuildType` scope does not imply (like any other Gradle DSL) it's scoped into it. 

You are effectively adding the same constants twice. 

Since this is an Android project, why not using AGP's native `buildConfigField` feature instead?:
```kotlin
android.buildFeatures.buildConfig = true
```

The equivalent-correct usage for this will be accessing `buildConfig.sourceSets`'s DSL, as it's documented in [here](https://github.com/gmazzo/gradle-buildconfig-plugin?tab=readme-ov-file#generate-constants-for-test-sourceset-or-any):
```kotlin
buildConfig {
   sourceSets.named("release") {
      buildConfigField("Boolean", "DEBUG", "false")
      buildConfigField("String", "BUILD_TYPE", "\"release\"")
   }
   sourceSets.named("debug") {
      buildConfigField("Boolean", "DEBUG", "true")
      buildConfigField("String", "BUILD_TYPE", "\"debug\"")
   }
}
```
