### ISSUE TITLE
Conditional or scoped generation based on buildTypes and flavor on Android?

### ISSUE THREAD

**Issue by aaulia** [gmazzo/gradle-buildconfig-plugin#35]
As the title says, I'm trying to mimic the default `buildConfigField`, where you can scope it based on buildType and/or flavor. I've tried using `buildConfig {}` like I would the default `buildConfigField` but in the end, all the `buildConfig {}` is being executed and I always ended up with the last `buildConfig {}` values. For example

```groovy
android {
    buildTypes {
        debug {
            buildConfig {
                buildConfigField("boolean", "DEBUG", "true")
            }
        }
        release {
            buildConfig {
                buildConfigField("boolean", "DEBUG", "false")
            }
        }
    }
}
```

It always set to `false` no matter what buildType I choose.

**Comment by gmazzo** [comment]
This plugin was envisioned as a generic port of Android's [buildConfigField](https://developer.android.com/studio/build/gradle-tips) feature, but never meant to replace it.

In the upcoming major release, Android-Kotlin will be supported by the plugin, but it will work in the same way that you can override values per variants.

The issue here is that you are violating scopes. `buildConfig` is not a closure/extension of an Android variant, but an DSL for the project, at root level. Yes, you can call it from whatever position in the DSL because it exists at project level, but the result will be the same.

Said that, once I release the latest major version, you will be able to achieve a similar behavior by using a correct DSL:
```kotlin
buildConfig {
     getByName("debug") {
           buildConfigField("boolean", "DEBUG", "true")
     }
     getByName("release") {
           buildConfigField("boolean", "DEBUG", "false")
     }
}
```

**Comment by valeriyo** [comment]
@gmazzo how does it actually work? I can't resolve `getByName(String)` method in there...

**Comment by gmazzo** [comment]
> @gmazzo how does it actually work? I can't resolve `getByName(String)` method in there...

I forgot to wrap it on `sourceSets` 🤦 , just edited the previous comment

**Comment by valeriyo** [comment]
I'm getting error: `DefaultBuildConfigSourceSet with name 'debug' not found.`

**Comment by valeriyo** [comment]
This is b...s... The only two source sets are `main` and `test`

**Comment by gmazzo** [comment]
> This is b...s... The only two source sets are `main` and `test`

Are you applying the Android plugin or the `java` one?
